name: release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release:
    uses: lumen-fx/candela/.github/workflows/build-package.yml@main
    with:
      candela-version: nightly
    secrets:
      lpm-token: ${{ secrets.LPM_TOKEN }}
